# Generated by Django 5.0.3 on 2024-03-23 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionarios',
            new_name='Funcionario',
        ),
    ]
