# Generated by Django 5.0.3 on 2024-03-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_funcionarios', '0002_rename_funcionarios_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='hora_fim',
            field=models.TextField(),
        ),
    ]
